version: '3'

services:
  vulnerability_database:
    container_name: vulnerability-engine-database
    build:
        context: ./
        dockerfile: ./database/Dockerfile.centos
    image: vulnerability-engine/database:latest
    restart: unless-stopped
    env_file:
      - ./conf/common.env
      - ./conf/database.env
    ports:
      - 5432:5432

  schema_spy:
    container_name: schema-spy
    privileged: true
    build:
      context: .
      dockerfile: ./Dockerfile.dbdocs
    depends_on:
      - vulnerability_database
    volumes:
      - ./scripts/output:/output
    env_file:
      - ./conf/database.env
    command: java -jar schemaspy.jar
