version: '3'

services:
  mock:
    volumes:
      - ./mock:/git
    security_opt:
      - label=disable
    working_dir: /git
    command: ["sleep", "infinity"]

  server:
    volumes:
      - ./server:/git
    security_opt:
      - label=disable
    working_dir: /git
    command: ["sleep", "infinity"]
