[tool.black]
line-length = 140
target-version = ["py311"]

[tool.semantic_release]
version_variables = ["common/constants.py:APP_VERSION"]
version_toml = ["pyproject.toml:tool.poetry.version"]
commit_author = "vmaas-bot <40663028+vmaas-bot@users.noreply.github.com>"

[tool.isort]
profile = "black"

[tool.poetry]
name = "vulnerability-engine"
version = "2.37.2"
description = ""
authors = ["RH Insights <mail@mail.com>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "~3.11"
python-dateutil = ">=2.8.2"
a2wsgi = "<1.10.1"
aiohttp = "3.9.3"
aiokafka = "0.8.1"
app-common-python = "0.2.5"
apscheduler = "3.7.0"
asyncpg = "0.29.0"
boto3 = "1.17.70"
botocore = "1.20.71"
flask = "^3.0.2"
gitpython = "3.1.41"
connexion = {version = "^3.0.6", extras = ["swagger-ui", "flask"]}
gunicorn = "^21.2.0"
peewee = "^3.17.1"
prometheus-client = "0.10.1"
psycopg2 = "2.9.3"
psycopg-pool = ">=3.2.1"
py-flags = "1.1.4"
pytz = "2021.1"
requests = "2.31.0"
watchtower = "1.0.6"
psycopg = {version = "3.1.6", extras = ["pool"]}
unleashclient = "^5.8.0"
uvicorn = "^0.27.1"
flask-limiter = "^3.5.0"
PyYAML = ">=6.0.1"
kafka-python = ">=2.0.2"

[tool.poetry.group.dev.dependencies]
pre-commit = "3.3.3"
pur = "^7.3.1"
pytest = "7.4.0"
pytest-asyncio = "0.15.1"
schema = "0.7.4"
testing-postgresql = "1.3.0"
tornado = "6.3.3"
python-box = "5.3.0"
insights-core = "^3.3.2"
pytest-cov = "2.11.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
