[tool.black]
line-length = 140
target-version = ["py38"]

[tool.semantic_release]
version_variables = ["common/constants.py:APP_VERSION"]
version_toml = ["pyproject.toml:tool.poetry.version"]
commit_author = "vmaas-bot <40663028+vmaas-bot@users.noreply.github.com>"

[tool.isort]
profile = "black"

[tool.poetry]
name = "vulnerability-engine"
version = "2.14.0"
description = ""
authors = [""]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "~3.8"
aiohttp = "3.8.5"
aiokafka = "0.7.2"
app-common-python = "0.2.5"
apscheduler = "3.7.0"
asyncpg = "0.24.0"
boto3 = "1.17.70"
botocore = "1.20.71"
flask = "2.2.5"
gitpython = "3.1.32"
connexion = {version = "2.14.0", extras = ["swagger-ui"]}
gunicorn = "20.0.2"
peewee = "3.14.4"
prometheus-client = "0.10.1"
psycopg2 = "2.9.3"
py-flags = "1.1.4"
pytz = "2021.1"
requests = "2.31.0"
tornado = "6.3.3"
watchtower = "1.0.6"
psycopg = {version = "3.1.6", extras = ["pool"]}
certifi = "2023.7.22"
pytest = "7.4.0"
unleashclient = "^5.8.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "3.3.3"
pur = "5.4.0"
pytest = "7.4.0"
pytest-asyncio = "0.15.1"
schema = "0.7.4"
testing-postgresql = "1.3.0"
python-box = "5.3.0"
pytest-flask = "1.2.0"
insights-core = "3.2.6"
pytest-cov = "2.11.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
