global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: engine
    static_configs:
      - targets:
        - ve_listener:8086
        - ve_manager:8000
        - ve_taskomatic:8085
    metric_relabel_configs:
      - source_labels: [endpoint]
        target_label: exported_endpoint
        replacement: $1
  - job_name: vulnerability-engine-evaluator-recalc
    static_configs:
      - targets:
        - ve_evaluator_recalc:8085
  - job_name: vulnerability-engine-evaluator-upload
    static_configs:
      - targets:
        - ve_evaluator_upload:8085
